### ISSUE TITLE
Feedback #1

### ISSUE THREAD

**Issue by Alvax10** [ayrton08/desafiom7-2.0#1]
Buenas ayrton! felicidades por llegar al desafío final del módulo 7! El backend funciona perfecto, y esto está bien ya que este era el punto necesario del desafío, a pesar de eso hay unos errores de frontend que me parecen necesarios corregir, te lo dejo en puntos a continuación:

1- A la hora de reportar estaría bueno que el mapa y el input con botón esten alineados al centro de la página, un simple align-self: "center" debería bastar:
![Screenshot from 2022-06-28 10-18-40](https://user-images.githubusercontent.com/64299010/176190289-2c822c8a-40d7-448a-a5ae-7a1317fd0a7a.png)

2- A la hora de editar la mascota se buguea un poco la ventanita y se ve medio raro, además de que se ve demasiado grande, en el screen no se puede entender bien a lo que me refiero de lo grande que se ve jaja:
![Screenshot from 2022-06-28 10-19-16](https://user-images.githubusercontent.com/64299010/176190491-e7bb2956-2dbc-4855-845c-89e7459aff5c.png)

3- El mapa se desborda de su contenedor, esto se puede arreglar facilmente poniendo esto `import "mapbox-gl/dist/mapbox-gl.css";` en la page/component que uses el mapa:
![Screenshot from 2022-06-28 10-22-06](https://user-images.githubusercontent.com/64299010/176190710-9a37f71f-c47b-4534-81fc-88773080022c.png)

4- Todo se ve bastaaante grande, estoy en una notebook por lo cual no es tan grande la pantalla y se ve todo como si estuviera con mucho zoom, en toda la página solo puedo ver una card:
![Screenshot from 2022-06-28 10-31-06](https://user-images.githubusercontent.com/64299010/176191502-c95d635e-3c4b-4385-8fc3-e6e5502cbd75.png)
Esto te pido que lo corrijas ya que aunque el desafío se basa en el backend más que nada, la página se tiene que seguir viendo bien y cómoda a la vista

5- Por último un detalle super menor (que ni hace falta que lo hagas, pero te lo marco por las dudas), que se pueda ver el nombre que escribe la persona en la barra del mapa en la card de la mascota, y si no escriben ninguno y quieren que tome su ubicación automáticamente (que eso está muy bueno, te felicito) agarre el nombre de la ubicación y lo ponga en la card

Si necesitas ayuda para cualquiera de estas cuestiones acordate que estamos en discord para ayudarte! Saludoss

**Comment by ayrton08** [comment]
Muchas gracias @Alvax10 por tu feedback, ahi implemente los cambios que me sugeriste, en el ultimo punto no se si logre entenderlo bien, pero agrege en la data de las cards el dato de la ubicacion. Espero haber logrado el objetivo, saludos!

**Comment by Alvax10** [comment]
Buenas @ayrton08 genial! Ahí chequeo todoo, sisi el punto 5 era hacer eso! 🙌🏻

**Comment by Alvax10** [comment]
Ahí quise meterme y no me deja volver a loguearme!

Este es el error que me salta:
![Screenshot from 2022-06-28 16-22-40](https://user-images.githubusercontent.com/64299010/176269389-50654eee-eac3-4b92-882d-637fa2a2cb6e.png)

Estaría bueno que se guarde tu token así no te tenes que loguear cada vez que entrás a la page !

**Comment by ayrton08** [comment]
@Alvax10 mala mia, toque unas validaciones pero ya lo arregle, si el token se guarda en el localStorage, ahora deberia funcionar bien 🙈😅

**Comment by Alvax10** [comment]
@ayrton08 no hay problema! ahí vuelvo a probar 🙌🏻

**Comment by Alvax10** [comment]
Genial @ayrton08 ! esta todo funcionando, un pequeño inconveniente nomás, cuando reportas una mascota con la locación automáticamente no aparece el nombre de la ubicación en la card, adjunto foto:

![Screenshot from 2022-06-28 17-00-34](https://user-images.githubusercontent.com/64299010/176274252-97e44217-0acd-4c2e-8cec-5d1748631b96.png)

Pero el desafío está aprobado! Felicidades 🥳 nos vemos en el siguiente módulo con react 🙌🏻 !
